/* 
* Copyright (c) 2013, Nordic Semiconductor ASA
* All rights reserved.
* 
* Redistribution and use in source and binary forms, with or without modification,
* are permitted provided that the following conditions are met:
* 
* - Redistributions of source code must retain the above copyright notice, this
*   list of conditions and the following disclaimer.
* 
* - Redistributions in binary form must reproduce the above copyright notice, this
*   list of conditions and the following disclaimer in the documentation and/or
*   other materials provided with the distribution.
* 
* - The name of Nordic Semiconductor ASA may not be used to endorse or promote
*   products derived from this software without specific prior written permission.
* 
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
* ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
* DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
* ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
* ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
* (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/**
* This file is autogenerated by nRFgo Studio .3031
*/

#include "services.h"
#include "lib_aci.h"

static bool is_hello_greeting_set_requested = false;
static bool is_hello_count_set_requested = false;
static bool is_tx_power_tx_power_level_set_requested = false;

static void *hello_greeting_set;
static uint8_t hello_greeting_set_size;
static void *hello_count_set;
static uint8_t hello_count_set_size;
static uint8_t tx_power_tx_power_level_set;

static bool hello_greeting_update_set(void)
{
  return(lib_aci_set_local_data(PIPE_HELLO_GREETING_SET, (void*)hello_greeting_set, hello_greeting_set_size));
}

void services_set_hello_greeting(void *src, int size)
{
  hello_greeting_set_size = size;
  hello_greeting_set = src;
  is_hello_greeting_set_requested = true;
  services_update_pipes();
}
static bool hello_count_update_set(void)
{
  return(lib_aci_set_local_data(PIPE_HELLO_COUNT_SET, (void*)hello_count_set, hello_count_set_size));
}

void services_set_hello_count(void *src, int size)
{
  hello_count_set_size = size;
  hello_count_set = src;
  is_hello_count_set_requested = true;
  services_update_pipes();
}
static bool tx_power_tx_power_level_update_set(void)
{
  return(lib_aci_set_local_data(PIPE_TX_POWER_TX_POWER_LEVEL_SET, (void*)&tx_power_tx_power_level_set, 1));
}

void services_set_tx_power_tx_power_level(uint8_t src)
{
  tx_power_tx_power_level_set = src;
  is_tx_power_tx_power_level_set_requested = true;
  services_update_pipes();
}

void services_update_pipes(void)
{
  if(is_hello_greeting_set_requested)
  {
    is_hello_greeting_set_requested = !(hello_greeting_update_set());
  }
  if(is_hello_count_set_requested)
  {
    is_hello_count_set_requested = !(hello_count_update_set());
  }
  if(is_tx_power_tx_power_level_set_requested)
  {
    is_tx_power_tx_power_level_set_requested = !(tx_power_tx_power_level_update_set());
  }
}

